version: '3.8'

services:
  datasource:
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
   image: minio/minio
   ports:
    - "9000:9000"
    - "9001:9001"
   volumes:
    - minio_storage:/data
   environment:
    MINIO_ROOT_USER: ykylas
    MINIO_ROOT_PASSWORD: 99Es13Al
   command: server --console-address ":9001" /data

volumes:
  pgdata:
  minio_storage:
